Reorganize

diff --git a/curlicue b/curlicue
--- a/curlicue
+++ b/curlicue
@@ -89,31 +89,10 @@ hmac_sha1() {
     printf '%s' "$2" | openssl dgst -sha1 -hmac "$1" -binary | openssl base64
 }
 
-# Here's where we start.
+# These are the two possible modes we can run in; get a new set of credentials
+# or make a request.
 
-method=GET
-oauth_timestamp="$(date +%s)"
-oauth_nonce="$(openssl rand -base64 12)"
-
-while getopts 'F:K:S:R:A:T:f:Pp:vu' opt; do
-    case "$opt" in
-        # Options for first-time setup
-        F) new_cred_file="$OPTARG";;
-        K) consumer_key="$OPTARG";;
-        S) consumer_secret="$OPTARG";;
-        R) request_token_url="$OPTARG";;
-        A) authorize_url="$OPTARG";;
-        T) access_token_url="$OPTARG";;
-        # Options for normal operation
-        f) load_cred_file "$OPTARG"; loaded=1;;
-        P) data_is_not_params=1;;
-        p) extra_params="$OPTARG";;
-        v) verbose=1;;
-        *) echo "Unknown option: $opt"; exit 2;;
-    esac
-done; shift $(($OPTIND-1))
-
-if test -n "$new_cred_file"; then
+setup_credentials() {
     test -n "$consumer_key" || read -p 'Consumer Key: ' consumer_key
     test -n "$consumer_secret" || read -p 'Consumer Secret: ' consumer_secret
     test -n "$request_token_url" || read -p 'Request Token URL: ' request_token_url
@@ -135,48 +114,76 @@ if test -n "$new_cred_file"; then
     paste -d '&' "$consumer_tmp" "$access_token_tmp" > "$new_cred_file"
     echo "Wrote $new_cred_file"
     rm -f "$consumer_tmp" "$request_token_tmp" "$access_token_tmp"
-    exit
-fi
+}
 
-# The remaining args in $@ go directly to curl. Fools that we are, we
-# attempt to parse them here. Only one URL is supported.
+oauth_curl() {
+    method=GET
+    oauth_timestamp="$(date +%s)"
+    oauth_nonce="$(openssl rand -base64 12)"
 
-for i; do
-    case "$prev" in
-        -d|--data|--data-raw) test -z "$data_is_not_params" && url_params="$i";;
-        -X|--request) method="$i";;
+    # The remaining args in $@ go directly to curl. Fools that we are, we
+    # attempt to parse them here. Only one URL is supported.
+
+    for i; do
+        case "$prev" in
+            -d|--data) test -z "$data_is_not_params" && url_params="$i";;
+            -X|--request) method="$i";;
+        esac
+        case "$i" in
+            -d|--data) method=POST;;
+            http*\?*) url="${i%%\?*}"; url_params="${i#*\?}";;
+            http*) url="$i";;
+        esac
+        prev="$i"
+    done
+
+    if test -z "$loaded"; then
+        cropped_url="${url#*://}"
+        host="${cropped_url%%/*}"
+        load_cred_file "$HOME/.curlicue/$host"
+    fi
+
+    if test -z "$oauth_consumer_key"; then
+        echo "Couldn't load a consumer key! Exiting." 1>&2
+        exit 1
+    fi
+
+    # This is where the magic happens.
+    params="$(mk_params "$url_params" | join_params '&')"
+    base_string="$(curl_encode "=$method" "=$url" "=$params")"
+    signing_key="$oauth_consumer_secret&$oauth_token_secret"
+    oauth_signature="$(hmac_sha1 "$signing_key" "$base_string")"
+    sig_params="$(curl_encode "oauth_signature=$oauth_signature")"
+    auth_header="$(mk_params "$sig_params" | quote_vals | join_params ',')"
+
+    if test -n "$verbose"; then
+        echo "Base string: $base_string" 1>&2
+        echo "Authorization: OAuth $auth_header" 1>&2
+    fi
+
+    curl -H "Authorization: OAuth $auth_header" "$@"
+}
+
+while getopts 'F:K:S:R:A:T:f:Pp:vu' opt; do
+    case "$opt" in
+        # Options for first-time setup
+        F) new_cred_file="$OPTARG";;
+        K) consumer_key="$OPTARG";;
+        S) consumer_secret="$OPTARG";;
+        R) request_token_url="$OPTARG";;
+        A) authorize_url="$OPTARG";;
+        T) access_token_url="$OPTARG";;
+        # Options for normal operation
+        f) load_cred_file "$OPTARG"; loaded=1;;
+        P) data_is_not_params=1;;
+        p) extra_params="$OPTARG";;
+        v) verbose=1;;
+        *) echo "Unknown option: $opt"; exit 2;;
     esac
-    case "$i" in
-        -d|--data|--data-raw) method=POST;;
-        http*\?*) url="${i%%\?*}"; url_params="${i#*\?}";;
-        http*) url="$i";;
-    esac
-    prev="$i"
-done
+done; shift $(($OPTIND-1))
 
-if test -z "$loaded"; then
-    cropped_url="${url#*://}"
-    host="${cropped_url%%/*}"
-    load_cred_file "$HOME/.curlicue/$host"
+if test -n "$new_cred_file"; then
+    setup_credentials
+else
+    oauth_curl "$@"
 fi
-
-if test -z "$oauth_consumer_key"; then
-    echo "Couldn't load a consumer key! Exiting." 1>&2
-    exit 1
-fi
-
-# This is where the magic happens.
-
-params="$(mk_params "$url_params" | join_params '&')"
-base_string="$(curl_encode "=$method" "=$url" "=$params")"
-signing_key="$oauth_consumer_secret&$oauth_token_secret"
-oauth_signature="$(hmac_sha1 "$signing_key" "$base_string")"
-sig_params="$(curl_encode "oauth_signature=$oauth_signature")"
-auth_header="$(mk_params "$sig_params" | quote_vals | join_params ',')"
-
-if test -n "$verbose"; then
-    echo "Base string: $base_string" 1>&2
-    echo "Authorization: OAuth $auth_header" 1>&2
-fi
-
-curl -H "Authorization: OAuth $auth_header" "$@"
